src/WebApps/GOS.Website/Models/SuppliersViewModels/TransferCreditsViewModel.cs
// Copyright (c) Crown Copyright (Department for Transport). Licensed under The MIT License (MIT).  See License file in the project root for license information.
using DfT.GOS.ReportingPeriods.Common.Models;
using DfT.GOS.Web.Validation;
using System.ComponentModel.DataAnnotations;

namespace DfT.GOS.Website.Models.SuppliersViewModels
{
    /// <summary>
    /// Represents the tranfer credit view model
    /// </summary>
    public class TransferCreditsViewModel
    {
        /// <summary>
        /// Tranaction id
        /// </summary>
        public int TransactionId { get; set; }

        /// <summary>
        /// Obligation period id
        /// </summary>
        public int ObligationPeriodId { get; set; }

        /// <summary>
        /// ID of the Supplier/Trader who is transferring the credits
        /// </summary>
        public int FromSupplierId { get; set; }

        /// <summary>
        /// ID of the recipient supplier/trader
        /// </summary>
        public int ToSupplierId { get; set; }

        /// <summary>
        /// Available credit balance
        /// </summary>
        public decimal AvailableCreditBalance { get; set; }

        /// <summary>
        /// Credits to be transferred
        /// </summary>
        [Display(Name = "Credits to be transferred")]
        [Range(0.01, (double)decimal.MaxValue, ErrorMessage = "The value is not valid for '{0}'")]
        [Decimal(2)]
        [Required]
        public decimal NumberOfCreditsToTransfer { get; set; }

        /// <summary>
        /// Falg to display admin contents
        /// </summary>
        public bool DisplaySupplierContext { get; internal set; }

        /// <summary>
        /// Supplier/trader name
        /// </summary>
        public string SupplierName { get; internal set; }

        /// <summary>
        /// Recipient supplier.trader name
        /// </summary>
        public string RecipientName { get; set; }

        /// <summary>
        /// Flag to indicate the balance summary service failure
        /// </summary>
        public bool BalanceServiceFailed { get; internal set; }

        /// <summary>
        /// Flag for if organisation is a Supplier
        /// </summary>
        public bool IsSupplier { get; set; }

        /// <summary>
        /// Flag for if organisation is a Trader
        /// </summary>
        public bool IsTrader { get; set; }

        /// <summary>
        /// Additional reference
        /// </summary>
        [Display(Name = "Additional reference")]
        [StringLength(40, ErrorMessage = "Additional reference cannot be more than 40 characters.")]
        public string AdditionalReference { get; set; }

        /// <summary>
        /// Obligation Period details
        /// </summary>
        public ObligationPeriod ObligationPeriod { get; set; }
    }
}

src/WebApps/GOS.Website/Controllers/TradingController.cs
// Copyright (c) Crown Copyright (Department for Transport). Licensed under The MIT License (MIT).  See License file in the project root for license information.
using System;
using System.Threading.Tasks;
using DfT.GOS.GhgBalanceView.API.Client.Services;
using DfT.GOS.GhgLedger.API.Client.Services;
using DfT.GOS.GhgLedger.Common.Exceptions;
using DfT.GOS.Organisations.API.Client.Models;
using DfT.GOS.Organisations.API.Client.Services;
using DfT.GOS.ReportingPeriods.API.Client.Services;
using DfT.GOS.Security.Claims;
using DfT.GOS.Security.Services;
using DfT.GOS.Website;
using DfT.GOS.Website.Controllers;
using DfT.GOS.Website.Models;
using DfT.GOS.Website.Models.SuppliersViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace GOS.Website.Controllers
{
    /// <summary>
    /// Controller for trading related http requests
    /// </summary>
    [Authorize(Roles = Roles.TradingRoles)]
    [Route("transfer")]
    public class TradingController : GosWebsiteControllerBase
    {
        #region Properties
        private IOrganisationsService OrganisationsService { get; set; }
        private IOptions<AppSettings> AppSettings { get; set; }
        private ILogger Logger { get; set; }
        private ITokenService TokenService { get; set; }
        private ILedgerService LedgerService { get; set; }
        private IBalanceViewService BalanceViewService { get; set; }
        private IReportingPeriodsService ReportingPeriodsService { get; set; }

        #endregion

        #region Constructor
        /// <summary>
        /// Constructor taking all dependent services
        /// </summary>
        /// <param name="appSettings">AppSettings (from configuration file)</param>
        /// <param name="organisationsService">OrganisationsService instance</param>
        /// <param name="logger">Logger instance</param>
        /// <param name="tokenService">TokenService instance</param>
        /// <param name="ledgerService">LedgerService instance</param>
        /// <param name="balanceViewService">BalanceViewService instance</param>
        /// <param name="reportingPeriods">ReportingPeriodsService instance</param>
        public TradingController(IOptions<AppSettings> appSettings
            , IOrganisationsService organisationsService
            , ILogger<TradingController> logger
            , ITokenService tokenService
            , ILedgerService ledgerService
            , IBalanceViewService balanceViewService
            , IReportingPeriodsService reportingPeriods)
        {
            this.AppSettings = appSettings;
            this.OrganisationsService = organisationsService;
            this.Logger = logger;
            this.TokenService = tokenService;
            this.LedgerService = ledgerService;
            this.BalanceViewService = balanceViewService;
            this.ReportingPeriodsService = reportingPeriods;
        }
        #endregion

        /// <summary>
        /// Gets the view containing a list of suppliers/traders
        /// </summary>
        /// <param name="supplierId">ID of supplier who is transferring the credits</param>
        /// <param name="obligationPeriod">Obligation period id</param>
        /// <param name="page">Page number</param>
        /// <param name="search">Search string to filter the supplier list</param>
        /// <returns>Paged results of supplier list</returns>
        [HttpGet("{supplierId}/obligationPeriod/{obligationPeriodId}")]
        public async Task<IActionResult> Index(int supplierId, int obligationPeriodId, [FromQuery]int page = 1, [FromQuery]string search = "")
        {
            var searchText = search ?? "";
            var token = await this.TokenService.GetJwtToken();
            var organisation = await this.OrganisationsService.GetOrganisation(supplierId, token);
            if (!organisation.HasResult && organisation.Result == null)
            {
                return NotFound("Organisation not found");
            }
            var obligationPeriod = await this.ReportingPeriodsService.GetObligationPeriod(obligationPeriodId);
            if (obligationPeriod == null)
            {
                return NotFound("Obligation period not found");
            }
            if (!this.User.CanAccessOrganisationDetails(supplierId))
            {
                return Forbid();
            }

            var suppliersResponse = await this.OrganisationsService.GetSuppliersAndTraders(page
                , this.AppSettings.Value.Pagination.ResultsPerPage
                , token
                , false
                , searchText);

            var viewModel = new TransferRecipientViewModel
            {
                Result = new UIPagedResult<Organisation>(suppliersResponse.Result
                , AppSettings.Value.Pagination.MaximumPagesToDisplay),
                SearchText = searchText,
                ObligationPeriodId = obligationPeriodId,
                ObligationPeriod = obligationPeriod,
                SupplierId = supplierId,
                SupplierName = organisation.Result.Name,
                DisplaySupplierContext = this.User.IsAdministrator(),
                IsSupplier = organisation.Result.IsSupplier,
                IsTrader = organisation.Result.IsTrader
            };
            ViewBag.Query = "&search=" + searchText;
            return View("SelectRecipient", viewModel);
        }

        /// <summary>
        /// Post method to filter the supplier list based on search text
        /// </summary>
        /// <param name="supplierId">ID of supplier who is transferring the credits</param>
        /// <param name="obligationPeriod">Obligation period id</param>
        /// <param name="searchText">Search string to filter the supplier list</param>
        /// <param name="page">Page number</param>
        /// <returns>Redirect action to Index</returns>
        [HttpPost("{supplierId}/obligationPeriod/{obligationPeriod}")]
        [ValidateAntiForgeryToken]
        public IActionResult Index(int supplierId, int obligationPeriod, [FromForm]string searchText, [FromQuery]int page = 1)
        {
            ViewBag.Query = "&search=" + searchText;
            return RedirectToAction("Index", new
            {
                supplierId = supplierId,
                obligationPeriod = obligationPeriod,
                page = page,
                search = searchText
            });
        }

        /// <summary>
        /// Returns the transfer credits view for the selected recipient
        /// </summary>
        /// <param name="supplierId">ID of supplier who is transferring the credits</param>
        /// <param name="tosupplierId">Id of recipient supplier/trader</param>
        /// <param name="obligationPeriodId">Obligation period id</param>
        /// <returns>Returns the Transfer credits view</returns>
        [HttpGet("obligationPeriod/{obligationPeriodId}/fromOrganisation/{supplierId}/toOrganisation/{tosupplierId}/TransferCredits")]
        public async Task<IActionResult> TransferCredits(int supplierId, int tosupplierId, int obligationPeriodId)
        {
            var token = await this.TokenService.GetJwtToken();
            if (!this.User.CanAccessOrganisationDetails(supplierId))
            {
                return Forbid();
            }
            var organisation = await this.OrganisationsService.GetOrganisation(supplierId, token);
            if (!organisation.HasResult && organisation.Result == null)
            {
                return NotFound("Organisation not found");
            }
            var recipient = await this.OrganisationsService.GetOrganisation(tosupplierId,
                 token);
            if (!recipient.HasResult && recipient.Result == null)
            {
                return NotFound("Recipient organisation not found");
            }
            var obligationPeriod = await this.ReportingPeriodsService.GetObligationPeriod(obligationPeriodId);
            if (obligationPeriod == null)
            {
                return NotFound("Obligation period not found");
            }

            var viewModel = new TransferCreditsViewModel
            {
                FromSupplierId = supplierId,
                ObligationPeriodId = obligationPeriodId,
                ToSupplierId = tosupplierId,
                SupplierName = organisation.Result.Name,
                RecipientName = recipient.Result.Name,
                DisplaySupplierContext = this.User.IsAdministrator(),
                IsSupplier = organisation.Result.IsSupplier,
                IsTrader = organisation.Result.IsTrader,
                ObligationPeriod = obligationPeriod
            };
            var balanceSummary = await this.BalanceViewService.GetSummary(organisation.Result.Id, obligationPeriodId, token);

            if (balanceSummary.HasResult && balanceSummary.Result != null)
            {
                viewModel.AvailableCreditBalance = balanceSummary.Result.BalanceCredits;
            }
            else
            {
                ModelState.AddModelError("", "Unable to transfer credits. If this issue persists contact system administrator.");
                viewModel.BalanceServiceFailed = true;
            }

            return View("TransferCredits", viewModel);
        }
        /// <summary>
        /// Posts the viewmodel with number of credits to be transferred
        /// </summary>
        /// <param name="supplierId">ID of supplier who is transferring the credits</param>
        /// <param name="tosupplierId">Id of recipient supplier/trader</param>
        /// <param name="obligationPeriodId">Obligation period id</param>
        /// <param name="model">TransferCreditsViewModel</param>
        /// <returns>Returns the confirmation view if successful</returns>

src/WebApps/GOS.Website/Views/Trading/SelectRecipient.cshtml
@* // Copyright (c) Crown Copyright (Department for Transport). Licensed under The MIT License (MIT).  See License file in the project root for license information. *@
@model DfT.GOS.Website.Models.SuppliersViewModels.TransferRecipientViewModel
@{
    ViewData["Title"] = $"Select recipient for transfer - {Model.ObligationPeriod.GetDescription()} - {Model.SupplierName}";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="govuk-breadcrumbs">
    <ol class="govuk-breadcrumbs__list">

        <li class="govuk-breadcrumbs__list-item">
            <a class="govuk-breadcrumbs__link" asp-controller="home" asp-action="home" asp-route-obligationPeriodId="@Model.ObligationPeriodId">Home</a>
        </li>
        @if (Model.DisplaySupplierContext)
        {
        <li class="govuk-breadcrumbs__list-item" aria-current="page">
            @if (Model.IsSupplier)
            {
                <a class="govuk-breadcrumbs__link" href="/suppliers/@Model.SupplierId/obligationperiod/@Model.ObligationPeriodId">@Model.SupplierName</a>
            }
            @if (Model.IsTrader)
            {
                <a class="govuk-breadcrumbs__link" href="/trader/@Model.SupplierId/obligationperiod/@Model.ObligationPeriodId">@Model.SupplierName</a>
            }
        </li>
        }
        <li class="govuk-breadcrumbs__list-item" aria-current="page">Transfer credits</li>
    </ol>
</div>
<h1 class="govuk-heading-l">Transfer Credits Out</h1>
<div class="govuk-inset-text">
    for the obligation period ending <br />
    <span class="govuk-label--xl govuk-label--light-blue">@Model.ObligationPeriod.EndDate.Value.ToString("dd/MM/yyyy")</span>
</div>
@using (Html.BeginForm("Index", "Trading", FormMethod.Post))
{
    @Html.HiddenFor(m => m.SupplierId)
    @Html.HiddenFor(m => m.ObligationPeriodId)
    <h2 class="govuk-heading-m">Select recipient</h2>
    <legend class="govuk-fieldset__legend">
        Select someone to transfer your credits gained in the obligation period ending @Model.ObligationPeriod.EndDate.Value.ToString("dd/MM/yyyy").
    </legend>
    <label class="govuk-label" for="searchtext">
        Search text
    </label>
    @Html.TextBoxFor(m => m.SearchText, new { @class = "govuk-input govuk-input--width-20", @type = "search", @name = "searchtext", @Id = "searchtext", @onsearch = "submit" })
    <button type="submit" class="govuk-button">
        Search
    </button>
    <table class="govuk-table">
        <thead class="govuk-table__head">
            <tr class="govuk-table__row">
                <th class="govuk-table__header" scope="col">Organisation</th>
                <th class="govuk-table__header" scope="col">Type</th>
            </tr>
        </thead>
        <tbody class="govuk-table__body">
            @foreach (var supplier in Model.Result.Result)
            {

                @if (supplier.Id != Model.SupplierId)
                {
                    <tr class="govuk-table__row">
                        <th class="govuk-table__header" scope="row">
                            <a class="govuk-link" href="/transfer/obligationPeriod/@Model.ObligationPeriodId/fromOrganisation/@Model.SupplierId/toOrganisation/@supplier.Id/TransferCredits">@supplier.Name</a>
                        </th>
                        @if (supplier.IsSupplier)
                        {
                            <td class="govuk-table__cell">Supplier</td>
                        }
                        @if (supplier.IsTrader)
                        {
                            <td class="govuk-table__cell">Trader</td>
                        }
                    </tr>
                }
            }
        </tbody>
    </table>
    @if (Model.Result.Result.Count == 0)
    {
        <div class="col-md-4 govuk-label">No suppliers to list</div>
    }
    @await Html.PartialAsync("_PaginationPartial", Model.Result)
    <br />
}

src/WebApps/GOS.Website/Views/Trading/TransferConfirmation.cshtml
@* // Copyright (c) Crown Copyright (Department for Transport). Licensed under The MIT License (MIT).  See License file in the project root for license information. *@
@model DfT.GOS.Website.Models.SuppliersViewModels.TransferCreditsViewModel
@{
    ViewData["Title"] = $"Submit transfer - {Model.ObligationPeriod.GetDescription()} - {Model.SupplierName}";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="govuk-breadcrumbs">
    <ol class="govuk-breadcrumbs__list">

        <li class="govuk-breadcrumbs__list-item">
            <a class="govuk-breadcrumbs__link" asp-controller="home" asp-action="home" asp-route-obligationPeriodId="@Model.ObligationPeriodId">Home</a>
        </li>
        @if (Model.DisplaySupplierContext)
        {
            <li class="govuk-breadcrumbs__list-item" aria-current="page">
                @if (Model.IsSupplier)
                {
                    <a class="govuk-breadcrumbs__link" href="/suppliers/@Model.FromSupplierId/obligationperiod/@Model.ObligationPeriodId">@Model.SupplierName</a>
                }
                @if (Model.IsTrader)
                {
                    <a class="govuk-breadcrumbs__link" href="/trader/@Model.FromSupplierId/obligationperiod/@Model.ObligationPeriodId">@Model.SupplierName</a>
                }
            </li>
        }
        <li class="govuk-breadcrumbs__list-item" aria-current="page">Transfer credits</li>
    </ol>
</div>
<h1 class="govuk-heading-l">Transfer Credits Out</h1>
<div class="govuk-inset-text">
    for the obligation period ending <br />
    <span class="govuk-label--xl govuk-label--light-blue">@Model.ObligationPeriod.EndDate.Value.ToString("dd/MM/yyyy")</span>
</div>
@await Html.PartialAsync("_ValidationSummary", ViewData.ModelState)
@using (Html.BeginForm("TransferredConfirmation", "Trading", FormMethod.Post))
{
    @Html.HiddenFor(m => m.FromSupplierId)
    @Html.HiddenFor(m => m.ToSupplierId)
    @Html.HiddenFor(m => m.ObligationPeriodId)
    @Html.HiddenFor(m => m.NumberOfCreditsToTransfer)
    @Html.HiddenFor(m => m.AvailableCreditBalance)
    @Html.HiddenFor(m => m.SupplierName)
    @Html.HiddenFor(m => m.RecipientName)
    @Html.HiddenFor(m => m.IsSupplier)
    @Html.HiddenFor(m => m.IsTrader)
    @Html.HiddenFor(m => m.AdditionalReference)
    <div class="govuk-form-group">
        <h2 class="govuk-heading-m">Credits</h2>
        <fieldset class="govuk-fieldset">
            <legend class="govuk-fieldset__legend" id="confirm-credit-transfer">
                Please confirm the details of the credit transfer.
            </legend>
            <div class="govuk-form-group">
                <table class="govuk-table">
                    <tbody class="govuk-table__body">
                        <tr class="govuk-table__row">
                            <td class="govuk-table__cell">
                                Transfer credits to
                            </td>
                            <td class="govuk-table__cell">
                                <p class="govuk-body govuk-!-font-weight-bold">@Model.RecipientName</p>

                            </td>
                        </tr>
                        <tr class="govuk-table__row">
                            <td class="govuk-table__cell">
                                Number of credits
                            </td>
                            <td class="govuk-table__cell">
                                <p class="govuk-body govuk-!-font-weight-bold">@Model.NumberOfCreditsToTransfer.ToString("#,##0.00")</p>

                            </td>
                        </tr>
                        <tr class="govuk-table__row">
                            <td class="govuk-table__cell">
                                Additional reference (optional)
                            </td>
                            <td class="govuk-table__cell">
                                <p class="govuk-body govuk-!-font-weight-bold">@Model.AdditionalReference</p>

                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <br />
            <br />
            <button type="submit" class="govuk-button">
                Submit transfer
            </button>
        </fieldset>
    </div>
}

src/WebApps/GOS.Website/Views/Trading/TransferCredits.cshtml
@* // Copyright (c) Crown Copyright (Department for Transport). Licensed under The MIT License (MIT).  See License file in the project root for license information. *@
@model DfT.GOS.Website.Models.SuppliersViewModels.TransferCreditsViewModel
@{
    ViewData["Title"] = $"Transfer credits - {Model.ObligationPeriod.GetDescription()} - {Model.SupplierName}";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="govuk-breadcrumbs">
    <ol class="govuk-breadcrumbs__list">

        <li class="govuk-breadcrumbs__list-item">
            <a class="govuk-breadcrumbs__link" asp-controller="home" asp-action="home" asp-route-obligationPeriodId="@Model.ObligationPeriodId">Home</a>
        </li>
        @if (Model.DisplaySupplierContext)
        {
            <li class="govuk-breadcrumbs__list-item" aria-current="page">
                @if (Model.IsSupplier)
                {
                    <a class="govuk-breadcrumbs__link" href="/suppliers/@Model.FromSupplierId/obligationperiod/@Model.ObligationPeriodId">@Model.SupplierName</a>
                }
                @if (Model.IsTrader)
                {
                    <a class="govuk-breadcrumbs__link" href="/trader/@Model.FromSupplierId/obligationperiod/@Model.ObligationPeriodId">@Model.SupplierName</a>
                }
            </li>
        }
        <li class="govuk-breadcrumbs__list-item" aria-current="page">Transfer credits</li>
    </ol>
</div>
<h1 class="govuk-heading-l">Transfer Credits Out</h1>
<div class="govuk-inset-text">
    for the obligation period ending <br />
    <span class="govuk-label--xl govuk-label--light-blue">@Model.ObligationPeriod.EndDate.Value.ToString("dd/MM/yyyy")</span>
</div>
@await Html.PartialAsync("_ValidationSummary", ViewData.ModelState)
@using (Html.BeginForm("TransferCredits", "Trading", FormMethod.Post))
{
    @Html.HiddenFor(m => m.FromSupplierId)
    @Html.HiddenFor(m => m.ToSupplierId)
    @Html.HiddenFor(m => m.ObligationPeriodId)
    @if (!Model.BalanceServiceFailed)
    {
        <div class="govuk-form-group">
            <h2 class="govuk-heading-m">Credits</h2>
            <fieldset class="govuk-fieldset">
                <legend class="govuk-fieldset__legend" id="">
                    You currently have @Model.AvailableCreditBalance.ToString("#,##0.00") credits available for transfer. Select the number of credits you wish to transfer to @Model.RecipientName
                </legend>
                <div class="govuk-form-group">
                    <label class="govuk-label" for="number-of-credits-to-transfer">Number of credits to transfer</label>
                    <span asp-validation-for="NumberOfCreditsToTransfer" class="govuk-error-message"></span>
                    @Html.TextBoxFor(m => m.NumberOfCreditsToTransfer, new { @class = "govuk-input govuk-!-width-one-third", @id = "number-of-credits-to-transfer", @name = "number-of-credits-to-transfer" })
                </div>
                <div class="govuk-form-group">
                    <label class="govuk-label" for="additional-reference">Additional reference (optional)</label>
                    <span asp-validation-for="AdditionalReference" class="govuk-error-message"></span>
                    @Html.TextBoxFor(m => m.AdditionalReference, new { @class = "govuk-input govuk-input--width-20", @id = "additional-reference", @name = "additional-reference" })
                </div>
                <br />
                <br />

                <button type="submit" class="govuk-button">
                    Continue
                </button>

            </fieldset>
        </div>
    }
}

src/WebApps/GOS.Website/Views/Trading/TransferredConfirmation.cshtml
@* // Copyright (c) Crown Copyright (Department for Transport). Licensed under The MIT License (MIT).  See License file in the project root for license information. *@
@model DfT.GOS.Website.Models.SuppliersViewModels.TransferredCreditsViewModel
@{
    ViewData["Title"] = $"Transfer successful - {Model.ObligationPeriod.GetDescription()} - {Model.SupplierName}";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="govuk-breadcrumbs">
    <ol class="govuk-breadcrumbs__list">

        <li class="govuk-breadcrumbs__list-item">
            <a class="govuk-breadcrumbs__link" asp-controller="home" asp-action="home" asp-route-obligationPeriodId="@Model.ObligationPeriodId">Home</a>
        </li>
        @if (Model.DisplaySupplierContext)
        {
        <li class="govuk-breadcrumbs__list-item" aria-current="page">
            @if (Model.IsSupplier)
            {
                <a class="govuk-breadcrumbs__link" href="/suppliers/@Model.FromSupplierId/obligationperiod/@Model.ObligationPeriodId">@Model.SupplierName</a>
            }
            @if (Model.IsTrader)
            {
                <a class="govuk-breadcrumbs__link" href="/trader/@Model.FromSupplierId/obligationperiod/@Model.ObligationPeriodId">@Model.SupplierName</a>
            }
        </li>
        }
        <li class="govuk-breadcrumbs__list-item" aria-current="page">Transfer credits</li>
    </ol>
</div>
<div class="govuk-panel govuk-panel--confirmation">
    <h2 class="govuk-panel__title">
        Credits successfully transferred out
    </h2>
    <div class="govuk-panel__body">
        Your reference number is @Model.TransactionId
        <br />
    </div>
</div>
<br />
<div class="row">
    <div class="col-md-4">
        <h2 class="govuk-heading-m">Credit transfer details</h2>
        <table class="govuk-table">
            <tbody class="govuk-table__body">
                <tr class="govuk-table__row">
                    <td class="govuk-table__cell">
                        Obligation period ending
                    </td>
                    <td class="govuk-table__cell">@Model.ObligationPeriod.EndDate.Value.ToString("dd/MM/yyyy")</td>
                </tr>
                <tr class="govuk-table__row">
                    <td class="govuk-table__cell">
                        Transfer credits to
                    </td>
                    <td class="govuk-table__cell">@Model.RecipientName</td>
                </tr>
                <tr class="govuk-table__row">
                    <td class="govuk-table__cell">
                        Number of credits
                    </td>
                    <td class="govuk-table__cell">@Model.NumberOfCreditsToTransfer.ToString("#,##0.00")</td>
                </tr>
                <tr class="govuk-table__row">
                    <td class="govuk-table__cell">
                        Additional reference (optional)
                    </td>
                    <td class="govuk-table__cell">@Model.AdditionalReference</td>
                </tr>
                <tr class="govuk-table__row">
                    <td class="govuk-table__cell">Remaining credit balance</td>
                    <td class="govuk-table__cell">@Model.BalanceCreditsAfterTransfer.ToString("#,##0.00")</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>