src/WebApps/GOS.Website/Controllers/CreditsController.cs
// Copyright (c) Crown Copyright (Department for Transport). Licensed under The MIT License (MIT).  See License file in the project root for license information.
using DfT.GOS.GhgApplications.API.Client.Services;
using DfT.GOS.GhgBalance.Common.Models;
using DfT.GOS.GhgBalanceView.API.Client.Services;
using DfT.GOS.GhgCalculations.API.Client.Services;
using DfT.GOS.GhgCalculations.Orchestration;
using DfT.GOS.GhgFuels.API.Client.Services;
using DfT.GOS.Http;
using DfT.GOS.Organisations.API.Client.Models;
using DfT.GOS.Organisations.API.Client.Services;
using DfT.GOS.ReportingPeriods.API.Client.Services;
using DfT.GOS.ReportingPeriods.Common.Models;
using DfT.GOS.Security.Claims;
using DfT.GOS.Security.Services;
using DfT.GOS.Website;
using DfT.GOS.Website.Models;
using DfT.GOS.Website.Models.CreditsViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GOS.Website.Controllers
{
    /// <summary>
    /// Controller for credits
    /// </summary>
    [Authorize(Roles = Roles.Administrator)]
    public class CreditsController : Controller
    {
        #region Properties

        private IReportingPeriodsService ReportingPeriodsService { get; set; }
        private IReviewApplicationsService ReviewApplicationsService { get; set; }
        private IApplicationsService ApplicationsService { get; set; }
        private IOrganisationsService OrganisationsService { get; set; }
        private IGhgFuelsService GhgFuelsService { get; set; }
        private ICalculationsService CalculationsService { get; set; }
        private IOptions<AppSettings> AppSettings { get; set; }
        private ITokenService TokenService { get; set; }
        private IBalanceViewService BalanceViewService { get; set; }

        #endregion Properties

        #region Constructors

        /// <summary>
        /// Constructor taking dependencies
        /// </summary>
        /// <param name="appSettings">The application settings configuration</param>
        /// <param name="reviewApplicationsService">The service for application reviews</param>
        /// <param name="applicationsService">The service for application details</param>
        /// <param name="calculationsService">The service for performing calculations</param>
        /// <param name="ghgFuelsService">The service for getting fuels</param>
        /// <param name="organisationsService">The service for getting organisation details</param>
        /// <param name="reportingPeriodsService">The service for getting obligation period details</param>
        /// <param name="tokenService">the token service</param>
        /// <param name="balanceViewService">the service for getting credit transfers</param>
        public CreditsController(IOptions<AppSettings> appSettings
            , IReviewApplicationsService reviewApplicationsService
            , IApplicationsService applicationsService
            , IGhgFuelsService ghgFuelsService
            , ICalculationsService calculationsService
            , IOrganisationsService organisationsService
            , IReportingPeriodsService reportingPeriodsService
            , ITokenService tokenService
            , IBalanceViewService balanceViewService)
        {
            this.AppSettings = appSettings;
            this.ReviewApplicationsService = reviewApplicationsService;
            this.ApplicationsService = applicationsService;
            this.GhgFuelsService = ghgFuelsService;
            this.CalculationsService = calculationsService;
            this.OrganisationsService = organisationsService;
            this.ReportingPeriodsService = reportingPeriodsService;
            this.TokenService = tokenService;
            this.BalanceViewService = balanceViewService;
        }

        #endregion Constructors

        #region Public Methods

        /// <summary>
        /// View for administrator to issue credits to suppliers
        /// </summary>
        /// <returns>Returns the Issue Credits view</returns>
        [Authorize(Roles = Roles.Administrator)]
        public async Task<IActionResult> Issue([FromQuery] int? selectedObligationPeriodId, [FromQuery]int page = 1)
        {
            if (selectedObligationPeriodId != null)
            {
                ViewBag.selectedObligationPeriodId = selectedObligationPeriodId;
            }
            var jwtToken = await this.TokenService.GetJwtToken();
            var pendingCreditIssue = new List<ApplicationReadyForIssueViewModel>();

            var result = await this.ReviewApplicationsService.GetApplicationsReadyForIssuePagedResult(jwtToken
              , this.AppSettings.Value.Pagination.ResultsPerPage
              , page);

            if (result != null
                && result.HasResult
                && result.Result.Result != null)
            {
                var supplierTasks = new List<Task<HttpObjectResponse<Organisation>>>();
                var calculationTasks = new List<Task<ApplicationCalculationSummaryResult>>();

                var fuelTypes = await this.GhgFuelsService.GetFuelTypes();

                var calculationOrchestrator = new ApplicationsCalculationOrchestrator(this.ApplicationsService
                    , this.CalculationsService
                    , fuelTypes
                    , jwtToken);

                var obligationPeriods = new List<ObligationPeriod>();

                foreach (var item in result.Result.Result)
                {
                    ObligationPeriod obligationPeriod;
                    if (obligationPeriods.Exists(op => op.Id == item.ObligationPeriodId))
                    {
                        obligationPeriod = obligationPeriods.Single(op => op.Id == item.ObligationPeriodId);
                    }
                    else
                    {
                        obligationPeriod = await this.ReportingPeriodsService.GetObligationPeriod(item.ObligationPeriodId);

                        if (obligationPeriod == null)
                        {
                            throw new ArgumentException($"No obligation period could be found with ID {item.ObligationPeriodId}", nameof(page));
                        }

                        obligationPeriods.Add(obligationPeriod);
                    }

                    var calulationResultTask = calculationOrchestrator.GetCalculationSummaryForApplication(item.ApplicationId
                        , item.SupplierOrganisationId
                        , item.ObligationPeriodId
                        , obligationPeriod.GhgThresholdGrammesCO2PerMJ.Value
                        , obligationPeriod.DeMinimisLitres
                        , obligationPeriod.NoDeMinimisLitres
                        , obligationPeriod.GhgLowVolumeSupplierDeductionKGCO2.Value);

                    calculationTasks.Add(calulationResultTask);

                    if (pendingCreditIssue.Count(x => x.SupplierId == item.SupplierOrganisationId) == 0)
                    {
                        var supplier = this.OrganisationsService.GetOrganisation(item.SupplierOrganisationId, jwtToken);
                        supplierTasks.Add(supplier);
                    }

                    var application = new ApplicationReadyForIssueViewModel()
                    {
                        ApplicationId = item.ApplicationId,
                        SupplierId = item.SupplierOrganisationId,
                        SubmittedDate = item.SubmittedDate,
                    };

                    pendingCreditIssue.Add(application);
                }

                //Populate the Supplier Names
                await Task.WhenAll(supplierTasks);

                supplierTasks.ForEach(task =>
                {
                    var updatedViewModel = pendingCreditIssue.Where(x => x.SupplierId == task.Result.Result.Id).Select(x =>
                    {
                        x.Supplier = task.Result.Result.Name;
                        return x;
                    }).ToList();
                });

                //Populate the calculation values
                await Task.WhenAll(calculationTasks);

                foreach (var task in calculationTasks)
                {
                    var pendingApproval = pendingCreditIssue.Single(pa => pa.ApplicationId == task.Result.ApplicationId);
                    pendingApproval.CreditsApplierFor = task.Result.Result.NetTotalCredits;
                }

            }
            var applications = new UIPagedResult<ApplicationReadyForIssueViewModel>()
            {
                Result = pendingCreditIssue,
                MaximumPagesToDisplay = this.AppSettings.Value.Pagination.MaximumPagesToDisplay,
                PageNumber = page,
                PageSize = this.AppSettings.Value.Pagination.ResultsPerPage,
            };

            if (result != null && result.HasResult && result.Result.Result != null)
            {
                applications.TotalResults = result.Result.TotalResults;
            }

            var viewModel = new PagedIssueCreditsViewModel(applications);
            return View("Issue", viewModel);
        }

        /// <summary>
        /// Handles a credit issue request
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = Roles.Administrator)]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Issue([FromQuery] int? selectedObligationPeriodId)
        {
            if (selectedObligationPeriodId != null)
            {
                ViewBag.selectedObligationPeriodId = selectedObligationPeriodId;
            }
            var jwtToken = await this.TokenService.GetJwtToken();
            var result = await this.ReviewApplicationsService.IssueCredits(jwtToken);
            if (result)
            {
                return View("IssueConfirmation");
            }

src/WebApps/GOS.Website/Views/Administrator/FurtherActions.cshtml
@* // Copyright (c) Crown Copyright (Department for Transport). Licensed under The MIT License (MIT).  See License file in the project root for license information. *@
@model DfT.GOS.Website.Models.AdministratorViewModels.FurtherActionsViewModel
@{
    ViewData["Title"] = "Administrator further actions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="govuk-breadcrumbs">
    <ol class="govuk-breadcrumbs__list">
        <li class="govuk-breadcrumbs__list-item">
            @if (Model.ObligationPeriodId == null)
            {
                <a class="govuk-breadcrumbs__link" asp-controller="home" asp-action="home">Home</a>
            }
            else
            {
                <a class="govuk-breadcrumbs__link" asp-controller="home" asp-action="home" asp-route-obligationPeriodId="@Model.ObligationPeriodId">Home</a>
            }
        </li>
        <li class="govuk-breadcrumbs__list-item" aria-current="page">Further actions</li>
    </ol>
</div>

<h1 class="govuk-heading-l">What would you like to do next?</h1>
<div class="govuk-grid-row">

    <div class="govuk-grid-column-one-half">
        <h2 class="govuk-heading-m">Account management</h2>

        <ul class="list govuk-list">
            <li><a class="govuk-list-item" asp-controller="Account" asp-action="Index" asp-route-obligationPeriodId="@ViewBag.selectedObligationPeriodId">View or amend my details</a></li>
            <li><a class="govuk-list-item" asp-action="ManageUsers" asp-route-selectedObligationPeriodId="@ViewBag.selectedObligationPeriodId">Manage admin user access</a></li>
        </ul>
    </div>

    <div class="govuk-grid-column-one-half">
        <h2 class="govuk-heading-m">System administration</h2>

        <ul class="list govuk-list">
            <li><a class="govuk-list-item" asp-controller="SystemAdministration" asp-action="GhgBalances" asp-route-selectedObligationPeriodId="@ViewBag.selectedObligationPeriodId">Manage GHG balances</a></li>
            <li>
                @if (@Model.ObligationPeriodId == null)
                {
                    <a class="govuk-list-item" asp-controller="SupplierSubmissions" asp-action="DownloadAllApplications">Download all application data</a>
                }
                else
                {
                    <a class="govuk-list-item" asp-controller="SupplierSubmissions" asp-action="DownloadAllApplications" asp-route-obligationPeriodId="@Model.ObligationPeriodId">Download all application data</a>
                }
            </li>
            <li><a class="govuk-list-item" asp-controller="SystemAdministration" asp-action="DownloadAllPerformanceData" asp-route-selectedObligationPeriodId="@ViewBag.selectedObligationPeriodId">Download all performance data</a></li>
        </ul>
    </div>
</div>
<div class="govuk-grid-row">

    <div class="govuk-grid-column-one-half">
        <h2 class="govuk-heading-m">Applications</h2>

        <ul class="list govuk-list">
            <li><a class="govuk-list-item" asp-controller="Credits" asp-action="Issue" asp-route-selectedObligationPeriodId="@ViewBag.selectedObligationPeriodId">Issue credits</a></li>
        </ul>
    </div>
</div>

src/WebApps/GOS.Website/Views/Administrator/ManageUsers.cshtml
@* // Copyright (c) Crown Copyright (Department for Transport). Licensed under The MIT License (MIT).  See License file in the project root for license information. *@
@using DfT.GOS.Website.Models.AdministratorViewModels
@model ManageAdminUsersViewModel
@{
    ViewData["Title"] = "Manage admin users";
}
<div class="govuk-breadcrumbs">
    <ol class="govuk-breadcrumbs__list">
        <li class="govuk-breadcrumbs__list-item">
            <a class="govuk-breadcrumbs__link" asp-controller="home" asp-action="home" asp-route-obligationPeriodId="@ViewBag.selectedObligationPeriodId">Home</a>
        </li>
        <li class="govuk-breadcrumbs__list-item" aria-current="page">Manage admin users</li>
    </ol>
</div>
<h1 class="govuk-heading-xl">Manage admin users</h1>
<div class="row">
    <div class="col-md-4">
        <form asp-route-returnUrl="@ViewData["ReturnUrl"]" asp-route-selectedObligationPeriodId="@ViewBag.selectedObligationPeriodId" method="post">
            @await Html.PartialAsync("_ValidationSummary", ViewData.ModelState)
            <div class="govuk-form-group">
                <fieldset class="govuk-fieldset" aria-describedby="account hint" role="group">
                    <label class="govuk-label" for="email">
                        Email address of user
                    </label>
                    <span class="govuk-hint">
                        Invite a user to create a GOS account with admin access or give admin access to an existing user
                    </span>

                    <span asp-validation-for="Email" class="govuk-error-message"></span>
                    @Html.TextBoxFor(m => m.Email, new { @class = "govuk-input govuk-input--width-20", @Email = "email", @Id = "email" })
                    <button type="submit" class="govuk-button">
                        Add User
                    </button>
                </fieldset>
            </div>
        </form>
    </div>
</div>
<h2 class="govuk-heading-m">Existing Users</h2>
<table class="govuk-table">
    <tbody class="govuk-table__body">
        @foreach (var user in Model.Users)
        {
            <tr class="govuk-table__row">
                <td class="govuk-table__cell">@user.FullName</td>
                <td class="govuk-table__cell">@user.Email</td>
                <td class="govuk-table__cell">
                    @if (Model.CurrentUserId != user.Id)
                    {<a href="/manageusers/@user.Id/Remove?selectedObligationPeriodId=@ViewBag.selectedObligationPeriodId">Remove</a>}
                </td>
            </tr>
        }
    </tbody>
</table>

src/WebApps/GOS.Website/Views/Administrator/ManageUsersConfirmation.cshtml
@* // Copyright (c) Crown Copyright (Department for Transport). Licensed under The MIT License (MIT).  See License file in the project root for license information. *@
@model DfT.GOS.Website.Models.AdministratorViewModels.ManageAdminUsersViewModel

@{
    ViewData["Title"] = "Invitation confirmation";
}
<div class="govuk-breadcrumbs">
    <ol class="govuk-breadcrumbs__list">
        <li class="govuk-breadcrumbs__list-item">
            <a class="govuk-breadcrumbs__link" asp-controller="home" asp-action="home" asp-route-obligationPeriodId="@ViewBag.selectedObligationPeriodId">Home</a>
        </li>
        <li class="govuk-breadcrumbs__list-item" aria-current="page">
            <a class="govuk-breadcrumbs__link" asp-action="ManageUsers" asp-route-selectedObligationPeriodId="@ViewBag.selectedObligationPeriodId">Manage admin users</a>
        </li>
        <li class="govuk-breadcrumbs__list-item" aria-current="page">Confirmation</li>
    </ol>
</div>

<div class="govuk-panel govuk-panel--confirmation">
    <h1 class="govuk-panel__title">
        @ViewData["Title"]
    </h1>
    <div class="govuk-panel__body">
        Your invitation has been sent to @Model.Email.<br/>
        They will be added to the existing administration users table once they accept and create their account.
    </div>
</div>

src/WebApps/GOS.Website/Views/Administrator/ManageUsersLinkedConfirmation.cshtml
@* // Copyright (c) Crown Copyright (Department for Transport). Licensed under The MIT License (MIT).  See License file in the project root for license information. *@
@model DfT.GOS.Website.Models.AdministratorViewModels.ManageAdminUsersViewModel

@{
    ViewData["Title"] = "User linked confirmation";
}
<div class="govuk-breadcrumbs">
    <ol class="govuk-breadcrumbs__list">
        <li class="govuk-breadcrumbs__list-item">
            <a class="govuk-breadcrumbs__link" asp-controller="home" asp-action="home" asp-route-obligationPeriodId="@ViewBag.selectedObligationPeriodId">Home</a>
        </li>
        <li class="govuk-breadcrumbs__list-item" aria-current="page">
            <a class="govuk-breadcrumbs__link" asp-action="ManageUsers" asp-route-selectedObligationPeriodId="@ViewBag.selectedObligationPeriodId">Manage admin users</a>
        </li>
        <li class="govuk-breadcrumbs__list-item" aria-current="page">Confirmation</li>
    </ol>
</div>

<div class="govuk-panel govuk-panel--confirmation">
    <h1 class="govuk-panel__title">
        @ViewData["Title"]
    </h1>
    <div class="govuk-panel__body">
        @Model.Email has been set as an Administrator.
    </div>
</div>

src/WebApps/GOS.Website/Views/Administrator/ManageUsersRemove.cshtml
@* // Copyright (c) Crown Copyright (Department for Transport). Licensed under The MIT License (MIT).  See License file in the project root for license information. *@
@using DfT.GOS.Website.Models.AdministratorViewModels;
@model AdminUserViewModel
@{
    ViewData["Title"] = "Remove admin user";
}
<div class="govuk-breadcrumbs">
    <ol class="govuk-breadcrumbs__list">
        <li class="govuk-breadcrumbs__list-item">
            <a class="govuk-breadcrumbs__link" asp-controller="home" asp-action="home" asp-route-obligationPeriodId="@ViewBag.selectedObligationPeriodId">Home</a>
        </li>
        <li class="govuk-breadcrumbs__list-item" aria-current="page">
            <a class="govuk-breadcrumbs__link" asp-action="ManageUsers" asp-route-selectedObligationPeriodId="@ViewBag.selectedObligationPeriodId">Manage admin users</a>
        </li>
        <li class="govuk-breadcrumbs__list-item" aria-current="page">Remove</li>
    </ol>
</div>
<div class="row">
    <div class="col-md-4">
        <form asp-route-returnUrl="@ViewData["ReturnUrl"]" asp-route-selectedObligationPeriodId="@ViewBag.selectedObligationPeriodId" method="post">

            <h1 class="govuk-panel__title">
                Confirm removal
            </h1>
            <div class="govuk-label">
                Account for @Model.FullName with Email @Model.Email will be removed from administrator role.
                Are you sure you want to proceed?
            </div>
            <br />
            <br />

            <a class="govuk-button" role="button" asp-action="ManageUsers" asp-route-selectedObligationPeriodId="@ViewBag.selectedObligationPeriodId">No</a>
            <button type="submit" class="govuk-button">
                Yes
            </button>
        </form>
    </div>
</div>