src/WebApps/GOS.Website/Models/AdministratorViewModels/DownloadAllPerformanceDataViewModel.cs
// Copyright (c) Crown Copyright (Department for Transport). Licensed under The MIT License (MIT).  See License file in the project root for license information.
using DfT.GOS.ReportingPeriods.Common.Models;

namespace DfT.GOS.Website.Models.AdministratorViewModels
{
    /// <summary>
    /// Download All Applications View Model
    /// </summary>
    public class DownloadAllPerformanceDataViewModel
    {
        public ObligationPeriod ObligationPeriod { get; set; }
    }
}

src/WebApps/GOS.Website/Controllers/SystemAdministrationController.cs
// Copyright (c) Crown Copyright (Department for Transport). Licensed under The MIT License (MIT).  See License file in the project root for license information.
using DfT.GOS.GhgApplications.API.Client.Services;
using DfT.GOS.GhgBalanceOrchestrator.API.Client.Models;
using DfT.GOS.GhgBalanceOrchestrator.API.Client.Services;
using DfT.GOS.GhgLedger.API.Client.Services;
using DfT.GOS.Identity.API.Client.Services;
using DfT.GOS.RtfoApplications.API.Client.Services;
using DfT.GOS.Security.Claims;
using DfT.GOS.Security.Services;
using DfT.GOS.Website;
using DfT.GOS.Website.Models;
using DfT.GOS.Website.Models.AdministratorViewModels;
using DfT.GOS.Website.Services;
using GOS.RtfoApplications.Common.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GOS.Website.Controllers
{
    /// <summary>
    /// Controller for System Administration specific actions
    /// </summary>
    [Authorize(Roles = Roles.Administrator)]
    public class SystemAdministrationController : Controller
    {
        #region Properties

        private IApplicationsService ApplicationsService { get; set; }
        private IUsersService UsersService { get; set; }
        private ILedgerService LedgerService { get; set; }
        private IBalanceAdministrationService BalanceAdministrationService { get; set; }
        private IRtfoPerformanceDataService RtfoPerformanceDataService { get; set; }
        private IPerformanceDataHelperService PerformanceDataHelperService { get; set; }
        private ITokenService TokenService { get; set; }
        private AppSettings AppSettings { get; set; }
        private ILogger<SystemAdministrationController> Logger { get; set; }

        #endregion Properties

        #region Constructors

        /// <summary>
        /// Constructor taking all dependencies
        /// </summary>
        /// <param name="applicationsService">the application service</param>
        /// <param name="balanceAdministrationService">The remote service for administering balances</param>
        /// <param name="rtfoPerformanceDataService">The remote service for accessing RTFO based performance data</param>
        public SystemAdministrationController(IApplicationsService applicationsService
            , IUsersService usersService
            , ILedgerService ledgerService
            , IBalanceAdministrationService balanceAdministrationService
            , IRtfoPerformanceDataService rtfoPerformanceDataService
            , IPerformanceDataHelperService performanceDataHelperService
            , ITokenService tokenService
            , IOptions<AppSettings> appSettings
            , ILogger<SystemAdministrationController> logger)
        {
            if (appSettings == null || appSettings.Value == null)
            {
                throw new ArgumentNullException("appSettings");
            }

            this.ApplicationsService = applicationsService ?? throw new ArgumentNullException("applicationsService");
            this.UsersService = usersService ?? throw new ArgumentNullException("usersService");
            this.LedgerService = ledgerService ?? throw new ArgumentNullException("ledgerService");
            this.BalanceAdministrationService = balanceAdministrationService ?? throw new ArgumentNullException("balanceAdministrationService");
            this.RtfoPerformanceDataService = rtfoPerformanceDataService ?? throw new ArgumentNullException("rtfoPerformanceDataService");
            this.PerformanceDataHelperService = performanceDataHelperService ?? throw new ArgumentNullException("performanceDataHelperService");
            this.TokenService = tokenService ?? throw new ArgumentNullException("tokenService");
            this.AppSettings = appSettings.Value;
            this.Logger = logger ?? throw new ArgumentNullException("logger");
        }

        #endregion Constructors

        #region Methods

        /// <summary>
        /// View for Managing GHG Balance data
        /// </summary>
        /// <returns>Returns the GHG Balances view</returns>
        [Authorize(Roles = Roles.Administrator)]
        [HttpGet]
        public IActionResult GhgBalances([FromQuery] int? selectedObligationPeriodId)
        {
            if (selectedObligationPeriodId != null)
            {
                ViewBag.selectedObligationPeriodId = selectedObligationPeriodId;
            }
            return View();
        }

        /// <summary>
        /// Handles an update ghg balance request
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = Roles.Administrator)]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> UpdateGhgBalances([FromQuery] int? selectedObligationPeriodId)
        {
            if (selectedObligationPeriodId != null)
            {
                ViewBag.selectedObligationPeriodId = selectedObligationPeriodId;
            }
            try
            {
                var result = await this.BalanceAdministrationService.UpdateCollections(await this.TokenService.GetJwtToken());
                if (result.HasResult)
                {
                    return RedirectToAction("UpdateGhgBalances", new { bulkUpdateUniqueId = result.Result, selectedObligationPeriodId });
                }
                else
                {
                    this.ModelState.AddModelError("balance", "Unable to update GHG balances at this time. Please try again later");
                    return View("GhgBalances");
                }
            }
            catch (Exception ex)
            {
                this.Logger.LogError(ex, "An error occurred whilst requesting update of the GHG balances.");
                this.ModelState.AddModelError("balance", "Unable to update GHG balances at this time. Please try again later");
                return View("GhgBalances");
            }
        }

        /// <summary>
        /// Retrieves details of the requested update ghg balance operation
        /// </summary>
        /// <param name="bulkUpdateUniqueId">Id of Collection Administration bulk update operation to check</param>
        /// <param name="getView">Function used to generate output based on the Collection Administration details</param>
        /// <returns>Returns the result of calling the supplied function with the retrieved Collection Administration details</returns>
        private async Task<IActionResult> UpdateGhgBalanceConfirmation(string bulkUpdateUniqueId, Func<CollectionAdministration, IActionResult> getView)
        {
            try
            {
                var jwtToken = await this.TokenService.GetJwtToken();
                var result = await this.BalanceAdministrationService.GetUpdateStatus(bulkUpdateUniqueId, jwtToken);

                if (result.HasResult)
                {
                    return getView(result.Result);
                }
                else
                {
                    this.Logger.LogWarning($"Unable to retrieve current status of Collection Administration with id '{bulkUpdateUniqueId}'.  Returned HTTP status code was '{result.HttpStatusCode}'.");
                    return getView(null);
                }
            }
            catch (Exception ex)
            {
                this.Logger.LogError(ex, "An error occurred whilst checking the status of a GHG bulk update.");
                return getView(null);
            }
        }

        /// <summary>
        /// View confirming the update ghg balance operation was succesfully made
        /// </summary>
        /// <param name="bulkUpdateUniqueId">Id of Collection Administration bulk update operation to check</param>
        /// <returns>Returns the Update GHG Balances confirmation view</returns>
        [Authorize(Roles = Roles.Administrator)]
        [HttpGet("SystemAdministration/UpdateGhgBalances/{bulkUpdateUniqueId}")]
        public async Task<IActionResult> UpdateGhgBalances(string bulkUpdateUniqueId, [FromQuery] int? selectedObligationPeriodId)
        {
            if (selectedObligationPeriodId != null)
            {
                ViewBag.selectedObligationPeriodId = selectedObligationPeriodId;
            }
            ViewBag.UpdateGhgBalanceConfirmationRefreshIntervalInSeconds = this.AppSettings.UpdateGhgBalanceConfirmationRefreshIntervalInSeconds;
            return await UpdateGhgBalanceConfirmation(bulkUpdateUniqueId, ca => View("UpdateGhgBalanceConfirmation", ca));
        }

        /// <summary>
        /// Partial View confirming the update ghg balance operation was succesfully made
        /// </summary>
        /// <param name="bulkUpdateUniqueId">Id of Collection Administration bulk update operation to check</param>
        /// <returns>Returns the Update GHG Balances confirmation partial view</returns>
        [Authorize(Roles = Roles.Administrator)]
        [HttpGet("SystemAdministration/UpdateGhgBalances/{bulkUpdateUniqueId}/Refresh")]
        public async Task<IActionResult> UpdateGhgBalancesPartial(string bulkUpdateUniqueId)
        {
            return await UpdateGhgBalanceConfirmation(bulkUpdateUniqueId, ca => PartialView("_UpdateGhgBalanceConfirmationPartial", ca));
        }

        /// <summary>
        /// View for download all performance data
        /// </summary>
        /// <returns>Returns the GHG Balances view</returns>
        [Authorize(Roles = Roles.Administrator)]
        [HttpGet]
        public IActionResult DownloadAllPerformanceData([FromQuery] int? selectedObligationPeriodId)
        {
            if (selectedObligationPeriodId != null)
            {
                ViewBag.selectedObligationPeriodId = selectedObligationPeriodId;
            }
            var viewModel = new DownloadAllPerformanceDataViewModel();

src/WebApps/GOS.Website/Views/SystemAdministration/DownloadAllPerformanceData.cshtml
@* // Copyright (c) Crown Copyright (Department for Transport). Licensed under The MIT License (MIT).  See License file in the project root for license information. *@
@model DfT.GOS.Website.Models.AdministratorViewModels.DownloadAllPerformanceDataViewModel
@{
    ViewData["Title"] = "Download performance data";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="govuk-breadcrumbs">
    <ol class="govuk-breadcrumbs__list">
        <li class="govuk-breadcrumbs__list-item">
            <a class="govuk-breadcrumbs__link" asp-controller="home" asp-action="home" asp-route-obligationPeriodId="@ViewBag.selectedObligationPeriodId">Home</a>
        </li>
        <li class="govuk-breadcrumbs__list-item" aria-current="page">Download all performance data</li>
    </ol>
</div>

<h1 class="govuk-heading-l">Download all performance data</h1>

<p class="govuk-body">Selecting the Download button will produce a CSV file, containing all performance data.</p>

<a class="govuk-button" role="button" href="/SystemAdministration/GeneratePerformanceDataDownload">Download</a>

src/WebApps/GOS.Website/Views/SystemAdministration/GhgBalances.cshtml
@* // Copyright (c) Crown Copyright (Department for Transport). Licensed under The MIT License (MIT).  See License file in the project root for license information. *@

@{
    ViewData["Title"] = "Administer GHG balances";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="govuk-breadcrumbs">
    <ol class="govuk-breadcrumbs__list">
        <li class="govuk-breadcrumbs__list-item">
            <a class="govuk-breadcrumbs__link" asp-controller="home" asp-action="home" asp-route-obligationPeriodId="@ViewBag.selectedObligationPeriodId">Home</a>
        </li>
        <li class="govuk-breadcrumbs__list-item" aria-current="page">GHG balance administration</li>
    </ol>
</div>
<h1 class="govuk-heading-l">GHG balance administration</h1>

<div class="govuk-warning-text">
    <span class="govuk-warning-text__icon" aria-hidden="true">!</span>
    <strong class="govuk-warning-text__text">
        <span class="govuk-warning-text__assistive">Warning</span>
        Selecting the Update GHG balances button will recalculate all balances for all suppliers across all GHG obligation periods.
    </strong>
</div>

@await Html.PartialAsync("_ValidationSummary", ViewData.ModelState)

@using (Html.BeginForm("UpdateGhgBalances", "SystemAdministration", new { selectedObligationPeriodId = ViewBag.selectedObligationPeriodId }, FormMethod.Post))
{
    <button type="submit" class="govuk-button">Update GHG balances</button>
}

src/WebApps/GOS.Website/Views/SystemAdministration/UpdateGhgBalanceConfirmation.cshtml
@* // Copyright (c) Crown Copyright (Department for Transport). Licensed under The MIT License (MIT).  See License file in the project root for license information. *@
@using DfT.GOS.GhgBalanceOrchestrator.API.Client.Models
@model CollectionAdministration

@{
    ViewData["Title"] = "Update GHG balances";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="govuk-breadcrumbs">
    <ol class="govuk-breadcrumbs__list">
        <li class="govuk-breadcrumbs__list-item">
            <a class="govuk-breadcrumbs__link" asp-controller="home" asp-action="home" asp-route-obligationPeriodId="@ViewBag.selectedObligationPeriodId">Home</a>
        </li>
        <li class="govuk-breadcrumbs__list-item" aria-current="page">GHG balance administration</li>
    </ol>
</div>
<h1 class="govuk-heading-l">GHG balance administration</h1>

<div id="updateGhgBalanceResult">
    @await Html.PartialAsync("_UpdateGhgBalanceConfirmationPartial", Model)
</div>

@if (Model != null)
{
    <noscript>
        <div class="govuk-body">
            Please <a class="govuk-link" href="/SystemAdministration/UpdateGhgBalances/@Model.Id">refresh this page</a> to check the current status of the GHG Balance Update.
        </div>
    </noscript>
}

<input type="hidden" id="UpdateGhgBalanceConfirmationRefreshIntervalInSeconds" value="@ViewBag.UpdateGhgBalanceConfirmationRefreshIntervalInSeconds" />
@Html.HiddenFor(m=>m.Id, new { id = "BulkUpdateUniqueId" })

@section Scripts {
    <script type="text/javascript" src="~/js/Views/SystemAdministration/updateGhgBalanceConfirmation.js"></script>
}

src/WebApps/GOS.Website/Views/SystemAdministration/_UpdateGhgBalanceConfirmationPartial.cshtml
@* // Copyright (c) Crown Copyright (Department for Transport). Licensed under The MIT License (MIT).  See License file in the project root for license information. *@
@using DfT.GOS.GhgBalanceOrchestrator.API.Client.Models
@model CollectionAdministration

@if (Model == null)
{
    <p class="govuk-body">Unable to retrieve the current status of the GHG update.  Please try again later.</p>
}
else
{
    @switch (Model.Status)
    {
        case CollectionAdministrationStatus.InProgress:

            <p class="govuk-body">The balances for all suppliers in all GHG obligations will be updated. This operation may take a number of minutes to complete.</p>

            <img class="govuk-loader" src="~/assets/images/ajax-loader.gif" id="AjaxLoader" alt="Update in progress" />

            <noscript>
                <style type="text/css">
                    #AjaxLoader {
                        display: none;
                    }
                </style>
            </noscript>

            break;

        case CollectionAdministrationStatus.Failed:

            <div class="govuk-panel govuk-panel--error">
                <h2 class="govuk-panel__title">
                    GHG balance recalculation has failed
                </h2>
                <div class="govuk-panel__body">
                    The system was unable to update balances for all suppliers in all GHG obligations. Please contact the system administrator.
                    <br />
                </div>
            </div>

            break;

        case CollectionAdministrationStatus.Succeeded:

            <div class="govuk-panel govuk-panel--confirmation">
                <h2 class="govuk-panel__title">
                    GHG balance recalculation has succeeded
                </h2>
                <div class="govuk-panel__body">
                    The balances for all suppliers in all GHG obligations have been updated.
                    <br />
                </div>
            </div>

            break;
    }
}